In [1]:
%load_ext sql

In [2]:
!pip install SQLALchemy==1.4.47
!pip install ipython-sql==0.4.1

Requirement already satisfied: SQLALchemy==1.4.47 in c:\users\xnote\appdata\local\programs\python\python313\lib\site-packages (1.4.47)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\xnote\appdata\local\programs\python\python313\lib\site-packages (from SQLALchemy==1.4.47) (3.2.1)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: ipython-sql==0.4.1 in c:\users\xnote\appdata\local\programs\python\python313\lib\site-packages (0.4.1)
Requirement already satisfied: prettytable<1 in c:\users\xnote\appdata\local\programs\python\python313\lib\site-packages (from ipython-sql==0.4.1) (0.7.2)
Requirement already satisfied: ipython>=1.0 in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython-sql==0.4.1) (9.0.2)
Requirement already satisfied: sqlalchemy>=0.6.7 in c:\users\xnote\appdata\local\programs\python\python313\lib\site-packages (from ipython-sql==0.4.1) (1.4.47)
Requirement already satisfied: sqlparse in c:\users\xnote\appdata\local\programs\python\python313\lib\site-packages (from ipython-sql==0.4.1) (0.5.3)
Requirement already satisfied: six in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython-sql==0.4.1) (1.17.0)
Requirement already satisfied: ipython-genutils>=0.1.0 in c:\users\xnote\appdata\local\programs\python\python313\lib\site-packages (from ipython-sql==0.4.1) (0.2.0)
Requirement already satisfied: colorama in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.4.6)
Requirement already satisfied: decorator in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (2.19.1)
Requirement already satisfied: stack_data in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\xnote\appdata\roaming\python\python313\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (5.14.3)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\xnote\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy>=0.6.7->ipython-sql==0.4.1) (3.2.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\xnote\appdata\roaming\python\python313\site-packages (from jedi>=0.16->ipython>=1.0->ipython-sql==0.4.1) (0.8.4)
Requirement already satisfied: wcwidth in c:\users\xnote\appdata\roaming\python\python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=1.0->ipython-sql==0.4.1) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in c:\users\xnote\appdata\roaming\python\python313\site-packages (from stack_data->ipython>=1.0->ipython-sql==0.4.1) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\xnote\appdata\roaming\python\python313\site-packages (from stack_data->ipython>=1.0->ipython-sql==0.4.1) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\xnote\appdata\roaming\python\python313\site-packages (from stack_data->ipython>=1.0->ipython-sql==0.4.1) (0.2.3)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%sql postgresql://user1:Dev12341234!@default-workgroup.885532410811.ap-northeast-2.redshift-serverless.amazonaws.com:5439/dev

In [12]:
%%sql

DROP TABLE IF EXISTS analytics.monthly_sales_by_industry;

 * postgresql://user1:***@default-workgroup.885532410811.ap-northeast-2.redshift-serverless.amazonaws.com:5439/dev
Done.

[]

In [13]:
%%sql

CREATE TABLE IF NOT EXISTS analytics.monthly_sales_by_industry(
    month VARCHAR(100) NOT NULL,
    card_tpbuz_nm_1 VARCHAR(100) NOT NULL,
    card_tpbuz_nm_2 VARCHAR(100) NOT NULL,
    total_amt BIGINT NOT NULL,
    total_cnt INT NOT NULL,
    avg_unit_price NUMERIC(14,2)
);

 * postgresql://user1:***@default-workgroup.885532410811.ap-northeast-2.redshift-serverless.amazonaws.com:5439/dev
Done.

[]

In [14]:
%%sql

INSERT INTO analytics.monthly_sales_by_industry
SELECT 
    TO_CHAR(ta_ymd, 'YYYY-MM') AS month,
    card_tpbuz_nm_1,
    card_tpbuz_nm_2,
    SUM(amt) AS total_amt,
    SUM(cnt) AS total_cnt,
    CASE WHEN SUM(CNT) = 0 THEN 0 ELSE ROUND(SUM(amt)::FLOAT / SUM(cnt), 2)END AS avg_unit_price
FROM raw_data.card_transaction
GROUP BY 1,2,3
ORDER By 1,2,3;

 * postgresql://user1:***@default-workgroup.885532410811.ap-northeast-2.redshift-serverless.amazonaws.com:5439/dev
981 rows affected.

[]

In [15]:
%%sql

SELECT *
FROM analytics.monthly_sales_by_industry
ORDER BY 1,2,3
LIMIT 10;

 * postgresql://user1:***@default-workgroup.885532410811.ap-northeast-2.redshift-serverless.amazonaws.com:5439/dev
10 rows affected.

[('2024-03', '공공/기업/단체', '공공기관', 1854182, 74, Decimal('25056.51')),
 ('2024-03', '공공/기업/단체', '기업', 1773887982, 48696, Decimal('36427.80')),
 ('2024-03', '공공/기업/단체', '단체', 582013306, 21526, Decimal('27037.69')),
 ('2024-03', '공공/기업/단체', '종교', 13736990, 14, Decimal('981213.57')),
 ('2024-03', '공연/전시', '경기관람', 4316338, 48, Decimal('89923.71')),
 ('2024-03', '공연/전시', '공연관람', 174657404, 12178, Decimal('14342.04')),
 ('2024-03', '공연/전시', '문화서비스', 8582530, 524, Decimal('16378.87')),
 ('2024-03', '공연/전시', '전시장', 5389122, 224, Decimal('24058.58')),
 ('2024-03', '미디어/통신', '기타결제', 10965944640, 244604, Decimal('44831.42')),
 ('2024-03', '미디어/통신', '방송/미디어', 452762886, 178, Decimal('2543611.72'))]

In [18]:
%%sql

SELECT DISTINCT month FROM analytics.monthly_sales_by_industry;

 * postgresql://user1:***@default-workgroup.885532410811.ap-northeast-2.redshift-serverless.amazonaws.com:5439/dev
12 rows affected.

[('2025-02',),
 ('2024-12',),
 ('2024-06',),
 ('2024-05',),
 ('2024-07',),
 ('2024-09',),
 ('2025-01',),
 ('2024-04',),
 ('2024-03',),
 ('2024-08',),
 ('2024-10',),
 ('2024-11',)]

In [3]:
%%sql
SELECT *
FROM analytics.monthly_sales_by_industry
WHERE month in ('2024-03')
ORDER BY 1,2,3;

 * postgresql://user1:***@default-workgroup.885532410811.ap-northeast-2.redshift-serverless.amazonaws.com:5439/dev
82 rows affected.

[('2024-03', '공공/기업/단체', '공공기관', 1854182, 74, Decimal('25056.51')),
 ('2024-03', '공공/기업/단체', '기업', 1773887982, 48696, Decimal('36427.80')),
 ('2024-03', '공공/기업/단체', '단체', 582013306, 21526, Decimal('27037.69')),
 ('2024-03', '공공/기업/단체', '종교', 13736990, 14, Decimal('981213.57')),
 ('2024-03', '공연/전시', '경기관람', 4316338, 48, Decimal('89923.71')),
 ('2024-03', '공연/전시', '공연관람', 174657404, 12178, Decimal('14342.04')),
 ('2024-03', '공연/전시', '문화서비스', 8582530, 524, Decimal('16378.87')),
 ('2024-03', '공연/전시', '전시장', 5389122, 224, Decimal('24058.58')),
 ('2024-03', '미디어/통신', '기타결제', 10965944640, 244604, Decimal('44831.42')),
 ('2024-03', '미디어/통신', '방송/미디어', 452762886, 178, Decimal('2543611.72')),
 ('2024-03', '미디어/통신', '시스템/통신', 537816, 8, Decimal('67227.00')),
 ('2024-03', '미디어/통신', '인터넷쇼핑', 2737662838, 113482, Decimal('24124.20')),
 ('2024-03', '생활서비스', '가례서비스', 8003498626, 53976, Decimal('148278.84')),
 ('2024-03', '생활서비스', '광고/인쇄/인화', 1819878106, 37632, Decimal('48359.86')),
 ('2024-03', '생활서비스', '교통서비스', 4163046, 70, Decimal('59472.09')),
 ('2024-03', '생활서비스', '금융상품/서비스', 2033838, 124, Decimal('16401.92')),
 ('2024-03', '생활서비스', '렌탈서비스', 41976018, 764, Decimal('54942.43')),
 ('2024-03', '생활서비스', '무점포서비스', 13729860, 4846, Decimal('2833.24')),
 ('2024-03', '생활서비스', '미용서비스', 7688668816, 152144, Decimal('50535.47')),
 ('2024-03', '생활서비스', '보안/운송', 231075192, 1720, Decimal('134346.04')),
 ('2024-03', '생활서비스', '부동산', 16596800, 572, Decimal('29015.38')),
 ('2024-03', '생활서비스', '사우나/휴게시설', 521626276, 38190, Decimal('13658.71')),
 ('2024-03', '생활서비스', '세탁/가사서비스', 1196741668, 47528, Decimal('25179.72')),
 ('2024-03', '생활서비스', '수리서비스', 666835686, 4368, Decimal('152663.85')),
 ('2024-03', '생활서비스', '여행/유학대행', 545772, 20, Decimal('27288.60')),
 ('2024-03', '생활서비스', '연료판매', 28475292364, 591492, Decimal('48141.47')),
 ('2024-03', '생활서비스', '전문서비스', 178137750, 2218, Decimal('80314.59')),
 ('2024-03', '생활서비스', '차량관리/서비스', 15391816390, 166194, Decimal('92613.55')),
 ('2024-03', '생활서비스', '회비/공과금', 2509266418, 49818, Decimal('50368.67')),
 ('2024-03', '소매/유통', '가전제품', 11464430432, 67818, Decimal('169047.01')),
 ('2024-03', '소매/유통', '건강/기호식품', 1014676704, 16870, Decimal('60146.81')),
 ('2024-03', '소매/유통', '기타용품', 71443756, 2208, Decimal('32356.77')),
 ('2024-03', '소매/유통', '방문판매', 438547158, 1820, Decimal('240959.98')),
 ('2024-03', '소매/유통', '사무/교육용품', 559711606, 52922, Decimal('10576.16')),
 ('2024-03', '소매/유통', '서적/도서', 1316894258, 44806, Decimal('29391.02')),
 ('2024-03', '소매/유통', '선물/완구', 1843927484, 41268, Decimal('44681.77')),
 ('2024-03', '소매/유통', '스포츠/레져용품', 2231493456, 22580, Decimal('98826.11')),
 ('2024-03', '소매/유통', '악기/공예', 153938362, 3394, Decimal('45356.03')),
 ('2024-03', '소매/유통', '유아용품', 268290938, 1352, Decimal('198440.04')),
 ('2024-03', '소매/유통', '음/식료품소매', 14406639390, 742858, Decimal('19393.53')),
 ('2024-03', '소매/유통', '의복/의류', 8697786764, 212596, Decimal('40912.28')),
 ('2024-03', '소매/유통', '인테리어/가정용품', 19009393320, 286600, Decimal('66327.26')),
 ('2024-03', '소매/유통', '제조/도매', 121285973428, 219514, Decimal('552520.45')),
 ('2024-03', '소매/유통', '종합소매점', 74655230530, 4370936, Decimal('17079.92')),
 ('2024-03', '소매/유통', '차량관리/부품', 1137197908, 5728, Decimal('198533.15')),
 ('2024-03', '소매/유통', '차량판매', 3152011304, 10992, Decimal('286755.03')),
 ('2024-03', '소매/유통', '패션잡화', 3436414962, 94668, Decimal('36299.65')),
 ('2024-03', '소매/유통', '화장품소매', 5812820186, 171252, Decimal('33943.08')),
 ('2024-03', '여가/오락', '숙박', 1297503302, 24478, Decimal('53006.92')),
 ('2024-03', '여가/오락', '요가/단전/마사지', 1299436038, 4996, Decimal('260095.28')),
 ('2024-03', '여가/오락', '일반스포츠', 3840320300, 83152, Decimal('46184.34')),
 ('2024-03', '여가/오락', '취미/오락', 1737887228, 197310, Decimal('8807.90')),
 ('2024-03', '음식', '간이주점', 3910146468, 75054, Decimal('52097.78')),
 ('2024-03', '음식', '고기요리', 10313512604, 214930, Decimal('47985.45')),
 ('2024-03', '음식', '닭/오리요리', 4443634238, 160518, Decimal('27683.09')),
 ('2024-03', '음식', '별식/퓨전요리', 3134366694, 139186, Decimal('22519.27')),
 ('2024-03', '음식', '부페', 560985918, 47444, Decimal('11824.17')),
 ('2024-03', '음식', '분식', 3711636894, 313028, Decimal('11857.20')),
 ('2024-03', '음식', '양식', 1686523444, 44686, Decimal('37741.65')),
 ('2024-03', '음식', '유흥주점', 1646002230, 14788, Decimal('111306.62')),
 ('2024-03', '음식', '음식배달서비스', 2472052, 142, Decimal('17408.82')),
 ('2024-03', '음식', '일식/수산물', 7924688346, 191102, Decimal('41468.37')),
 ('2024-03', '음식', '제과/제빵/떡/케익', 4756146592, 401068, Decimal('11858.70')),
 ('2024-03', '음식', '중식', 2504360010, 118792, Decimal('21081.89')),
 ('2024-03', '음식', '커피/음료', 6276277890, 895106, Decimal('7011.77')),
 ('2024-03', '음식', '패스트푸드', 5060712804, 341236, Decimal('14830.54')),
 ('2024-03', '음식', '한식', 28144037072, 961512, Decimal('29270.60')),
 ('2024-03', '음식', '휴게소/대형업체', 36876208, 2260, Decimal('16316.91')),
 ('2024-03', '의료/건강', '기타의료', 2312692486, 8778, Decimal('263464.63')),
 ('2024-03', '의료/건강', '수의업', 2463563612, 35554, Decimal('69290.76')),
 ('2024-03', '의료/건강', '의약/의료품', 20651677036, 816942, Decimal('25279.25')),
 ('2024-03', '의료/건강', '일반병원', 35605787604, 645544, Decimal('55156.25')),
 ('2024-03', '의료/건강', '종합병원', 8136298, 2298, Decimal('3540.60')),
 ('2024-03', '의료/건강', '특화병원', 14357474788, 139006, Decimal('103286.73')),
 ('2024-03', '학문/교육', '기술/직업교육학원', 205074876, 420, Decimal('488273.51')),
 ('2024-03', '학문/교육', '기타교육', 1048062634, 2668, Decimal('392827.07')),
 ('2024-03', '학문/교육', '독서실/고시원', 418772504, 5272, Decimal('79433.33')),
 ('2024-03', '학문/교육', '예체능계학원', 2239931540, 14402, Decimal('155529.20')),
 ('2024-03', '학문/교육', '외국어학원', 3469486048, 10604, Decimal('327186.54')),
 ('2024-03', '학문/교육', '유아교육', 4202635792, 27922, Decimal('150513.42')),
 ('2024-03', '학문/교육', '입시학원', 5874596570, 17956, Decimal('327166.22')),
 ('2024-03', '학문/교육', '자동차학원', 602069746, 1162, Decimal('518132.31'))]